=== BorisProkhorenko/FourthTask/src/main/resources/candiesSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="urn:Test.Namespace"
            xmlns="urn:Test.Namespace"
            elementFormDefault="qualified">

    <xsd:element name="Candies">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="caramel-candy" type="Caramel" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="chocolate-candy" type="Chocolate" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="Candy">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="energy" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:ID" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="Caramel">
        <xsd:complexContent>
            <xsd:extension base="Candy">
                <xsd:sequence>
                    <xsd:element name="caramel" type="TypeOfCaramel"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="Chocolate">
        <xsd:complexContent>
            <xsd:extension base="Candy">
                <xsd:sequence>
                    <xsd:element name="chocolate" type="TypeOfChocolate"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:simpleType name="TypeOfCaramel">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="LOLLIPOP"></xsd:enumeration>
            <xsd:enumeration value="SOFT"></xsd:enumeration>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="TypeOfChocolate">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="WHITE"></xsd:enumeration>
            <xsd:enumeration value="BITTER"></xsd:enumeration>
            <xsd:enumeration value="MILK"></xsd:enumeration>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== BorisProkhorenko/FourthTask/src/test/java/resources/candies.xml
<?xml version="1.0" encoding="UTF-8"?>
<Candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="urn:Test.Namespace"
         xsi:schemaLocation="urn:Test.Namespace /candiesSchema.xsd">

    <caramel-candy id="i-1">
        <name>Apple Pops</name>
        <energy>0.382</energy>
        <caramel>LOLLIPOP</caramel>
    </caramel-candy>

    <chocolate-candy id="i-2">
        <name>Hershey's Kisses</name>
        <energy>0.535</energy>
        <chocolate>MILK</chocolate>
    </chocolate-candy>

</Candies>

=== BorisProkhorenko/FourthTask/src/test/java/resources/incorrect.xml
<?xml version="1.0" encoding="UTF-8"?>
<Candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="urn:Test.Namespace"
         xsi:schemaLocation="urn:Test.Namespace /candiesSchema.xsd">

    <caramel-candy>
        <name>Apple Pops</name>
        <energy>0.382</energy>
        <caramel>LOLLIPOP</caramel>
    </caramel-candy>
    <Candy>
        <name>Apple Pops</name>
        <energy>0.382</energy>
    </Candy>

    <chocolate-candy>
        <name>Hershey's Kisses</name>
        <energy>0.535</energy>
        <chocolate>MILK</chocolate>
    </chocolate-candy>

</Candies>
